### PR TITLE
Network Scan / Debug

### PR DESCRIPTION
**Pull request by macpie**
Hi Benoit,

This should help to scan / debug networks. I have made a simple test suite to show case the enhancements.

### CODE REVIEW

**Comment by benoitc** [comment]
thanks for the patch!

I think the patch  `gen_udp:send/4`  could be improved though : 

- The patch function use a static timeout of 1000 where the `nat_upnpv1:discover/1` is increasing it exponentially starting from 250ms. 
- the patched  function return` timeout` where `ok`  is expected by  `nat_upnpv1:discover/1`  and then doesn't retry.

Not sure yet how it could be done. I quite like the idea of logging the actions. Maybe it would be easier to do that explicitly ?

**Comment by macpie** [comment]
Sure, I'll work on the timeout stuff. What did you mean by ` Maybe it would be easier to do that explicitly ?` ?

**Comment by benoitc** [comment]
@macpie well I was thinking to do the logging directly inside the code instead of using the intercept module. But since it's only for debug better tot ry to fix the current patch maybe :)

**Comment by macpie** [comment]
This should fix the timeout stuff also  as I am not handling it anymore, the nat code does. It is indeed cleaner with the trace!

**Comment by benoitc** [comment]
Thanks! looks good to me too. I will recheck in the morning and add upnp 2 to the scan as well since it is now supported in the latest master.

**Comment by macpie** [comment]
@benoitc done

**Comment by benoitc** [comment]
Thanks, merged. I will release 0.2 on hex

**Pull request merged**
